// Compiled by Babel
// ** DO NOT EDIT THIS FILE DIRECTLY **
//
'use strict';

require('should');

describe('Dummy test', function () {
  it('is a dummy', function () {
    true.should.equal(true);
  });
});
//# sourceMappingURL=test.js.map
