// Compiled by Babel
// ** DO NOT EDIT THIS FILE DIRECTLY **
//
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * Helper definitions for interfacing with Nagios
 * https://www.nagios.com
 */

var Nagios = function Nagios() {
  _classCallCheck(this, Nagios);
};

// Constant values obtained from
// https://github.com/NagiosEnterprises/nagioscore/
// include/common.h

// Host states


exports.default = Nagios;
Nagios.HostState = {
  UP: 0,
  DOWN: 1,
  UNREACHABLE: 2
};

Nagios.ServiceState = {
  OK: 0,
  WARNING: 1,
  CRITICAL: 2,
  UNKNOWN: 3
};

Nagios.ReturnCode = Nagios.ServiceState;

Nagios.StateType = {
  SOFT: 0,
  HARD: 1
};
//# sourceMappingURL=nagios.js.map
