// Compiled by Babel
// ** DO NOT EDIT THIS FILE DIRECTLY **
//
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

var _terminalOutputBuffer = require('./terminal-output-buffer');

var _terminalOutputBuffer2 = _interopRequireDefault(_terminalOutputBuffer);

var _nagios = require('./nagios');

var _nagios2 = _interopRequireDefault(_nagios);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var Station = function () {
  function Station(config) {
    _classCallCheck(this, Station);

    var configKeys = ['id', 'name', 'type', 'default_app', 'possible_apps'];

    var _iteratorNormalCompletion = true;
    var _didIteratorError = false;
    var _iteratorError = undefined;

    try {
      for (var _iterator = configKeys[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
        var configKey = _step.value;

        if (!config.hasOwnProperty(configKey)) {
          if (configKey === 'id') {
            throw new Error('Attempted to initialize station with config missing id');
          }
          throw new Error('Attempted to initialize station ' + config.id + ' missing config key ' + configKey);
        }

        this[configKey] = config[configKey];
      }
    } catch (err) {
      _didIteratorError = true;
      _iteratorError = err;
    } finally {
      try {
        if (!_iteratorNormalCompletion && _iterator.return) {
          _iterator.return();
        }
      } finally {
        if (_didIteratorError) {
          throw _iteratorError;
        }
      }
    }

    this.state = Station.UNKNOWN;
    this.status = '';
    this.app = this.default_app;
    this.switching_app = '';
    this.outputBuffer = new _terminalOutputBuffer2.default();
  }

  /**
   * Updates the state of the station
   *
   * Returns true if the state was changed
   *
   * @param {Object} stationStatus - MKLivestatus status of the station
   * @returns {boolean}
   */


  _createClass(Station, [{
    key: 'updateFromMKLivestatus',
    value: function updateFromMKLivestatus(stationStatus) {
      // stationStatus:
      // id: station.id,
      // state: Nagios.HostState.DOWN,
      // state_type: Nagios.StateType.HARD,
      // app_state: Nagios.ServiceState.UNKNOWN,
      // app_state_type: Nagios.StateType.HARD,
      // app_id: '',

      var changes = false;
      if (this.app !== stationStatus.app_id) {
        this.app = stationStatus.app_id;
        changes = true;
      }

      // todo: STARTING_STATION, STARTING_APP and STOPPING timeout
      // todo: SWITCHING_APP timeout

      if (this.state === Station.ERROR) {
        return false;
      }

      if (stationStatus.state === _nagios2.default.HostState.UNREACHABLE) {
        this.setErrorState('Station unreachable');
        return true;
      }

      if (this.state === Station.UNKNOWN) {
        if (stationStatus.state === _nagios2.default.HostState.DOWN) {
          this.setOffState();
          return true;
        } else if (stationStatus.state === _nagios2.default.HostState.UP) {
          this.setOnState();
          return true;
        }
      } else if (this.state === Station.ON) {
        if (stationStatus.state === _nagios2.default.HostState.DOWN) {
          this.setOffState();
          return true;
        }
      } else if (this.state === Station.OFF) {
        if (stationStatus.state === _nagios2.default.HostState.UP) {
          this.setOnState();
          return true;
        }
      } else if (this.state === Station.STOPPING) {
        if (stationStatus.state === _nagios2.default.HostState.DOWN) {
          this.setOffState();
          return true;
        }
      } else if (this.state === Station.STARTING_STATION) {
        if (stationStatus.state === _nagios2.default.HostState.UP) {
          this.setStartingAppState();
          return true;
        }
      } else if (this.state === Station.STARTING_APP) {
        if (stationStatus.app_state === _nagios2.default.ServiceState.OK) {
          this.setOnState();
          return true;
        }
      } else if (this.state === Station.SWITCHING_APP) {
        if (this.switching_app !== '' && this.switching_app === stationStatus.app_id) {
          this.setOnState();
          return true;
        }

        if (stationStatus.state === _nagios2.default.HostState.DOWN) {
          this.setOffState();
          return true;
        }
      }

      return changes;
    }

    /**
     * Transitions the station to the "waiting to start" state
     *
     * @return {boolean} The transition was successful
     */

  }, {
    key: 'setQueuedToStartState',
    value: function setQueuedToStartState() {
      if (this.state === Station.OFF) {
        this.state = Station.STARTING_STATION;
        this.status = 'Waiting to start...';
        return true;
      }
      return false;
    }

    /**
     * Transitions the station to the "starting" state
     *
     * @return {boolean} The transition was successful
     */

  }, {
    key: 'setStartingState',
    value: function setStartingState() {
      if (this.state === Station.OFF || this.state === Station.STARTING_STATION) {
        this.state = Station.STARTING_STATION;
        this.status = 'Starting...';
        return true;
      }
      return false;
    }

    /**
     * Transitions the station to the "starting app" state
     *
     * @return {boolean} The transition was sucessful
     */

  }, {
    key: 'setStartingAppState',
    value: function setStartingAppState() {
      if (this.state === Station.STARTING_STATION) {
        this.state = Station.STARTING_APP;
        this.status = 'Waiting for app...';
        return true;
      }
      return false;
    }

    /**
     * Transitions the station to the "waiting to stop" state
     *
     * @return {boolean} The transition was succesful
     */

  }, {
    key: 'setQueuedToStopState',
    value: function setQueuedToStopState() {
      if (this.state === Station.ON) {
        this.state = Station.STOPPING;
        this.status = 'Waiting to stop...';
        return true;
      }
      return false;
    }

    /**
     * Transitions the station to the "stopping" state
     *
     * @return {boolean} The transition was successful
     */

  }, {
    key: 'setStoppingState',
    value: function setStoppingState() {
      if (this.state === Station.OFF || this.state === Station.STOPPING) {
        this.state = Station.STOPPING;
        this.status = 'Stopping...';
        return true;
      }
      return false;
    }

    /**
     * Transitions the station to the "queued to change app" state
     *
     * @param appID {string}
     * @return {boolean} The transition was successful
     */

  }, {
    key: 'setQueuedToChangeAppState',
    value: function setQueuedToChangeAppState(appID) {
      if (this.state === Station.ON && appID !== this.app) {
        this.state = Station.SWITCHING_APP;
        this.status = 'Waiting to change app...';
        this.switching_app = appID;
        return true;
      }
      return false;
    }

    /**
     * Transitions the station to the "changing app" state
     *
     * @param appID {string}
     * @return {boolean} The transition was successful
     */

  }, {
    key: 'setChangingAppState',
    value: function setChangingAppState(appID) {
      if ((this.state === Station.ON || this.state === Station.SWITCHING_APP) && appID !== this.app) {
        this.state = Station.SWITCHING_APP;
        this.status = 'Opening ' + appID + '...';
        this.switching_app = appID;
        return true;
      }
      return false;
    }
  }, {
    key: 'setOnState',
    value: function setOnState() {
      this.state = Station.ON;
      this.status = '';
      this.switching_app = '';
    }
  }, {
    key: 'setOffState',
    value: function setOffState() {
      this.state = Station.OFF;
      this.status = '';
      this.switching_app = '';
    }

    /**
     * Transitions the station to the "error" state
     *
     * @param reason {string} Description of the error
     */

  }, {
    key: 'setErrorState',
    value: function setErrorState(reason) {
      this.state = Station.ERROR;
      this.status = reason;
    }
  }]);

  return Station;
}();

// Station states

exports.default = Station;
Station.UNKNOWN = 'unk';
Station.OFF = 'off';
Station.ON = 'on';
Station.STOPPING = 'stopping';
Station.STARTING_STATION = 'starting_station';
Station.STARTING_APP = 'starting_app';
Station.SWITCHING_APP = 'switching_app';
Station.ERROR = 'error';
//# sourceMappingURL=station.js.map
