// Compiled by Babel
// ** DO NOT EDIT THIS FILE DIRECTLY **
//
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * Represents a single Preset with its associated data
 */
var Preset = function () {

  /**
   * Constructor. Instead of calling this directly use PresetStore::createPreset
   *
   * @param {PresetStore} presetStore
   *  Store where the preset will be persisted
   */
  function Preset(presetStore) {
    _classCallCheck(this, Preset);

    this.store = presetStore;
    this.id = null;
    this.name = null;
    this.clearAllStationApps();
  }

  /**
   * Clears app assignments for all stations
   */


  _createClass(Preset, [{
    key: "clearAllStationApps",
    value: function clearAllStationApps() {
      this.stationData = {};
    }

    /**
     * Set the app for a station
     *
     * @param {String} stationID
     * @param {String} appID
     */

  }, {
    key: "setStationApp",
    value: function setStationApp(stationID, appID) {
      this.stationData[stationID] = appID;
    }

    /**
     * Get the app for a station
     *
     * @param {String} appID
     * @return {Object}
     */

  }, {
    key: "getStationApp",
    value: function getStationApp(appID) {
      return this.stationData[appID];
    }

    /**
     * Saves the preset in the store
     *
     * If the preset's id was null one will be set after calling this function.
     *
     * @return {Promise.<Preset>}
     */

  }, {
    key: "save",
    value: function save() {
      var _this = this;

      if (this.id === null) {
        return this.store.insertPreset(this).then(function (id) {
          _this.id = id;
          return _this;
        });
      }
      return this.store.updatePreset(this);
    }

    /**
     * Deletes the preset from the store
     *
     * The id field is nulled after deleting.
     *
     * @return {Promise.<Preset>}
     */

  }, {
    key: "remove",
    value: function remove() {
      var _this2 = this;

      return this.store.removePreset(this).then(function () {
        _this2.id = null;
      });
    }
  }]);

  return Preset;
}();

exports.default = Preset;
//# sourceMappingURL=preset.js.map
