'use strict';

var gulp = require('gulp');
var babel = require("gulp-babel");
var sourcemaps = require("gulp-sourcemaps");
var wrapper = require('gulp-wrapper');
var exec = require('child_process').exec;

function compile() {

  return gulp.src("src/**/*.js")
      .pipe(sourcemaps.init())
      .pipe(babel({presets: ["es2015"]}))
      .pipe(wrapper({
        header: `// Compiled by Babel
// ** DO NOT EDIT THIS FILE DIRECTLY **
//
`
      }))
      .pipe(sourcemaps.write("."))
      .pipe(gulp.dest("app"));
}

gulp.task('compile', compile);

gulp.task('compile:watch', function () {
  gulp.watch(['src/**/*.js'], ['compile']);
});

gulp.task('default', ['compile', 'compile:watch']);

gulp.task('server', function (cb) {
  // I could use nodemon to watch + restart the server
  var child = exec('node app/main.js');
  child.stderr.on('data', function(data){
    console.error(data);
  });
  child.stdout.on('data', function(data){
    console.log(data);
  });
  child.on('close', function(code) {
    console.log("Server exited with code = " + code);
  });
  child.on('error', function (error) {
    console.log(error); // to see your exception details in the console
    // if you are on production, maybe you can send the exception details to your
    // email as well ?
  });

});
